# Project information
site_name: 'Accompanist'
site_description: 'A group of libraries to help write Jetpack Compose apps.'
site_author: 'Google'
site_url: 'https://google.github.io/accompanist/'
edit_uri: 'tree/main/docs/'
remote_branch: gh-pages

docs_dir: docs-gen

# Repository
repo_name: 'Accompanist'
repo_url: 'https://github.com/google/accompanist'

# Navigation
nav:
  - 'Overview': index.md
  - 'Pager layouts':
    - 'Guide': pager.md
    - 'API': api/pager/
  - 'Swipe Refresh':
    - 'Guide': swiperefresh.md
    - 'API': api/swiperefresh/
  - 'Placeholder':
    - 'Guide': placeholder.md
    - 'Foundation API': api/placeholder/
    - 'Material API': api/placeholder-material/
  - 'Flow layouts':
    - 'Guide': flowlayout.md
    - 'API': api/flowlayout/
  - 'Contributing': contributing.md
  - 'Maintainers':
    - 'Update guide': updating.md

# Configuration
theme:
  name: 'material'
  language: 'en'
  icon:
    logo: material/music-clef-treble
  palette:
    primary: 'black'
    accent: 'deep orange'
  font:
    text: 'Roboto'
    code: 'JetBrains Mono'

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
